// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC5Bo3bSWYyuaTKPiLS6jodJgyzKemu_14',
    appId: '1:434255871832:web:1115bf80804647ac97ef2d',
    messagingSenderId: '434255871832',
    projectId: 'dokan-3afb6',
    authDomain: 'dokan-3afb6.firebaseapp.com',
    storageBucket: 'dokan-3afb6.firebasestorage.app',
    measurementId: 'G-HVSPN77ZHX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCsEdawvGhpCvtfrbX24AM35W1xQKRmQ3A',
    appId: '1:434255871832:android:8f0d4c7a1b4a1ad597ef2d',
    messagingSenderId: '434255871832',
    projectId: 'dokan-3afb6',
    storageBucket: 'dokan-3afb6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCawG_O_QDFcIMImbns4SqcDM1JBH1TDxY',
    appId: '1:434255871832:ios:7eee4c5890692b6297ef2d',
    messagingSenderId: '434255871832',
    projectId: 'dokan-3afb6',
    storageBucket: 'dokan-3afb6.firebasestorage.app',
    iosBundleId: 'com.dokan.dokan',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC5Bo3bSWYyuaTKPiLS6jodJgyzKemu_14',
    appId: '1:434255871832:web:df8571fef65f427697ef2d',
    messagingSenderId: '434255871832',
    projectId: 'dokan-3afb6',
    authDomain: 'dokan-3afb6.firebaseapp.com',
    storageBucket: 'dokan-3afb6.firebasestorage.app',
    measurementId: 'G-EK9CV4SHHK',
  );

}